name: halcyon

services:
    halcyon-api:
        image: halcyon-api:dev
        build:
            context: .
            dockerfile: src/Halcyon.Api/Dockerfile
            args:
                VERSION: 1.0.0-docker
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_HTTP_PORTS: 8080
            ASPNETCORE_HTTPS_PORTS: 8081
            ConnectionStrings__Database: Host=postgres;Port=5432;Database=halcyon;Username=postgres;Password=password
            Email__SmtpServer: mailhog
        ports:
            - 5257:8080
            - 7257:8081
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:16.4-alpine
        user: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        healthcheck:
            test: [ 'CMD', 'pg_isready' ]
            interval: 10s
            timeout: 5s
            retries: 3

    mailhog:
        image: mailhog/mailhog:v1.0.1
        environment:
            MH_STORAGE: maildir
            MH_MAILDIR_PATH: /home/mailhog
        ports:
            - 1025:1025
            - 8025:8025
        volumes:
            - mailhog:/home/mailhog

volumes:
    postgres:
    mailhog:
