services:
  halcyon-api:
    image: ${DOCKER_REGISTRY-}halcyon-api
    build:
      context: .
      dockerfile: src/Halcyon.Api/Dockerfile
      args:
        VERSION: 1.0.0-docker
    environment:
      ConnectionStrings__Database: Host=host.docker.internal;Port=5432;Database=halcyon;Username=postgres;Password=password
      ConnectionStrings__RabbitMq: amqp://guest:guest@host.docker.internal:5672
      Email__SmtpServer: host.docker.internal
      Serilog__WriteTo__Seq__Args__serverUrl: http://host.docker.internal:5341
      Serilog__MinimumLevel__Override__Microsoft.AspNetCore.DataProtection: Error
    restart: always
    networks:
      - halcyon-network
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:16.4-alpine
    user: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - halcyon-network
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    hostname: local
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - halcyon-network
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  mailhog:
    image: mailhog/mailhog:v1.0.1
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
      # MH_AUTH_FILE: /home/mailhog-auth
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - halcyon-network
    volumes:
      - mailhog:/home/mailhog
      # MailHog bcrypt test
      # - ./mailhog-auth:/home/mailhog-auth

  seq:
    image: datalust/seq:2024.3
    environment:
      ACCEPT_EULA: Y
      # echo 'password' | docker run --rm -i datalust/seq config hash
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: QPeG8pGvEJu2fECM8zZ5EDQM/mXBxL4X5+GzwHMfhn8KILjH8Z6sBtIY47FhAWVFZchQC3S6SyBSZmQFzvS2HET+WrTqniK4GEJTL7S3sfqJ
      SEQ_API_CANONICALURI: http://localhost:5341
    ports:
      - 5341:80
    networks:
      - halcyon-network
    volumes:
      - seq:/data

volumes:
  postgres:
    name: halcyon-postgres
  rabbitmq:
    name: halcyon-rabbitmq
  mailhog:
    name: halcyon-mailhog
  seq:
    name: halcyon-seq

networks:
  halcyon-network:
    name: halcyon-network
    driver: bridge
