name: halcyon

services:
    halcyon-api:
        image: halcyon-api:dev
        build:
            context: .
            dockerfile: src/Halcyon.Api/Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_HTTP_PORTS: 8080
            ASPNETCORE_HTTPS_PORTS: 8081
            ConnectionStrings__Database: Host=host.docker.internal;Port=5432;Database=halcyon-api;Username=postgres;Password=password
            Email__SmtpServer: host.docker.internal
            Serilog__MinimumLevel__Override__Microsoft.AspNetCore.DataProtection: Error
            Serilog__WriteTo__Seq__Args__serverUrl: http://host.docker.internal:5341
            OTEL_EXPORTER_OTLP_ENDPOINT: http://host.docker.internal:5341/ingest/otlp/v1/traces
            OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
        ports:
            - 5257:8080
            - 7257:8081
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:17.2
        user: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: [ 'CMD', 'pg_isready' ]
            interval: 10s
            timeout: 5s
            retries: 3

    maildev:
        image: maildev/maildev:2.1.0
        environment:
            MAILDEV_MAIL_DIRECTORY: /tmp
        ports:
            - 1025:1025
            - 1080:1080
        volumes:
            - maildev:/tmp
        restart: always

    seq:
        image: datalust/seq:2024.3
        environment:
            ACCEPT_EULA: Y
            SEQ_API_CANONICALURI: http://localhost:5341
        ports:
            - 5341:80
        volumes:
            - seq:/data
        restart: always

volumes:
    postgres:
        name: halcyon-postgres
    maildev:
        name: halcyon-maildev
    seq:
        name: halcyon-seq
