name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Set Environment Variables
        run: |
          echo "VERSION=$(echo ${{ env.GITVERSION_SEMVER }})" >> $GITHUB_ENV
          echo "STAGE=$(echo ${{ env.GITVERSION_ESCAPEDBRANCHNAME }})" >> $GITHUB_ENV

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build
        run: |
          docker build . -t ${{ secrets.REGISTRY_URL }}/halcyon-dotnet:${{ env.VERSION }} --build-arg VERSION=${{ env.VERSION }} --build-arg STAGE=${{ env.STAGE }}
          docker push ${{ secrets.REGISTRY_URL }}/halcyon-dotnet:${{ env.VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: halcyon
          template: ./azuredeploy.json
          parameters: plan="halcyon-plan"
            web="halcyon-dotnet-${{ env.STAGE }}-web"
            registryUrl="${{ secrets.REGISTRY_URL }}"
            registryUserName="${{ secrets.REGISTRY_USERNAME }}"
            registryPassword="${{ secrets.REGISTRY_PASSWORD }}"
            dbHost="${{ secrets.DB_HOST }}"
            dbUser="${{ secrets.DB_USER }}"
            dbPassword="${{ secrets.DB_PASSWORD }}"
            dbDatabase="halcyon-dotnet-${{ env.STAGE }}"
            dbSSL="${{ secrets.DB_SSL }}"
            emailSmtpServer="${{ secrets.EMAIL_SMTP_SERVER }}"
            emailSmtpPort="${{ secrets.EMAIL_SMTP_PORT }}"
            emailSmtpUserName="${{ secrets.EMAIL_SMTP_USERNAME }}"
            emailSmtpPassword="${{ secrets.EMAIL_SMTP_PASSWORD }}"
            emailNoReplyAddress="${{ secrets.EMAIL_NO_REPLY_ADDRESS }}"
            jwtSecurityKey="${{ secrets.JWT_SECURITY_KEY }}"
            jwtIssuer="${{ secrets.JWT_ISSUER }}"
            jwtAudience="${{ secrets.JWT_AUDIENCE }}"
            jwtExpiresIn="${{ secrets.JWT_EXPIRES_IN }}"
            seedEmailAddress="${{ secrets.SEED_EMAIL_ADDRESS }}"
            seedPassword="${{ secrets.SEED_PASSWORD }}"

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: halcyon-dotnet-${{ env.STAGE }}-web
          images: ${{ secrets.REGISTRY_URL }}/halcyon-dotnet:${{ env.VERSION }}

      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear
