name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      EXTEND_ESLINT: true

      REACT_APP_GA_MEASUREMENTID: ${{ secrets.GA_MEASUREMENTID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Set Environment Variables
        run: |
          echo "VERSION=$(echo ${{ env.GITVERSION_SEMVER }})" >> $GITHUB_ENV
          echo "STAGE=$(echo ${{ env.GITVERSION_ESCAPEDBRANCHNAME }})" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet restore
          yarn --cwd Halcyon.Web/ClientApp version --new-version ${{ env.REACT_APP_VERSION }} --no-git-tag-version
          dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/halcyon-web -p:Version=${{ env.REACT_APP_VERSION }}

      - name: Deploy
        uses: azure/webapps-deploy@v1
        with:
          app-name: halcyon-web-${{ env.STAGE }}
          publish-profile: ${{ secrets.AZURE_PUBLISHPROFILE }}
          package: ${{ env.DOTNET_ROOT }}/halcyon-web
