name: CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Set Environment Variables
        run: |
          echo "REACT_APP_VERSION=$(echo ${{ env.GITVERSION_SEMVER }})" >> $GITHUB_ENV
          echo "REACT_APP_STAGE=$(echo ${{ env.GITVERSION_ESCAPEDBRANCHNAME }})" >> $GITHUB_ENV

      - name: Build
        env:
          EXTEND_ESLINT: true
        run: |
          dotnet restore
          yarn --cwd Halcyon.Web/ClientApp version --new-version ${{ env.REACT_APP_VERSION }} --no-git-tag-version
          dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/halcyon-web -p:Version=${{ env.REACT_APP_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name "halcyon-${{ env.REACT_APP_STAGE }}" \
            --location "${{ secrets.AZURE_LOCATION }}"

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: halcyon-${{ env.REACT_APP_STAGE }}
          template: ./azuredeploy.json
          parameters: version="${{ env.REACT_APP_VERSION }}"
            stage="${{ env.REACT_APP_STAGE }}"
            sqlUserName="${{ secrets.SQL_USERNAME }}"
            sqlPassword="${{ secrets.SQL_PASSWORD }}"
            emailSmtpServer="${{ secrets.EMAIL_SMTP_SERVER }}"
            emailSmtpPort="${{ secrets.EMAIL_SMTP_PORT }}"
            emailSmtpUserName="${{ secrets.EMAIL_SMTP_USERNAME }}"
            emailSmtpPassword="${{ secrets.EMAIL_SMTP_PASSWORD }}"
            emailNoReplyAddress="${{ secrets.EMAIL_NO_REPLY_ADDRESS }}"
            jwtSecurityKey="${{ secrets.JWT_SECURITY_KEY }}"
            jwtIssuer="${{ secrets.JWT_ISSUER }}"
            jwtAudience="${{ secrets.JWT_AUDIENCE }}"
            jwtExpiresIn="${{ secrets.JWT_EXPIRES_IN }}"
            seedEmailAddress="${{ secrets.SEED_EMAIL_ADDRESS }}"
            seedPassword="${{ secrets.SEED_PASSWORD }}"

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: halcyon-${{ env.REACT_APP_STAGE }}-web
          package: ${{ env.DOTNET_ROOT }}/halcyon-web

      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear
