name: Main Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_DEV_COLLECT_TELEMETRY: no

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
                  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Determine Version
        run: |
          dotnet tool restore
          dotnet gitversion /output buildserver /updateprojectfiles

      - name: Build and test
        run: |
          dotnet build
          dotnet test

      # - name: Install azd
      #   uses: Azure/setup-azd@v1.0.0

      # - name: Install .NET Aspire workload
      #   run: dotnet workload install aspire

      # - name: Log in with Azure (Federated Credentials)
      #   run: |
      #     azd auth login `
      #       --client-id "$Env:AZURE_CLIENT_ID" `
      #       --federated-credential-provider "github" `
      #       --tenant-id "$Env:AZURE_TENANT_ID"
      #   shell: pwsh

      # - name: Provision Infrastructure
      #   run: azd provision --no-prompt
      #   env:
      #     AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}

      # - name: Deploy Application
      #   run: azd deploy --no-prompt
