name: Preview Build and Deploy

on:
    push:
        branches: ['feature/**', 'bugfix/**']
    workflow_dispatch:

jobs:
    build:
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

            - name: Log in to GitHub container registry
              uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}

            - name: Lowercase the repo name and username
              run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

            - name: Build and push container image to registry
              uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
              with:
                  push: true
                  tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
                  file: ./src/Halcyon.Api/Dockerfile
                  build-args: |
                      VERSION=${{ github.sha }}

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: Preview
            # url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
            url: ${{ vars.URL }}

        steps:
            - name: Lowercase the repo name and username
              run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
