name: Preview Build and Deploy

on:
  push:
    branches:
      - "feature/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish "src/Halcyon.Api/Halcyon.Api.csproj" --configuration Release --output ./api -p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: halcyon-api
          path: ./api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Preview
      url: ${{ vars.URL }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: halcyon-api

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZUREAPPSERVICE_APPNAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
