name: Preview Build and Publish

on:
    pull_request:
        branches: ['main']
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4

            - name: Build and test
              run: |
                  dotnet build "halcyon-api.sln"
                  dotnet test "halcyon-api.sln"

    publish:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup .NET
              uses: actions/setup-dotnet@v4

            - name: Determine Version
              id: version_step
              run: |
                  dotnet tool restore
                  dotnet gitversion /updateprojectfiles

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}

            - name: Lowercase the repo name and username
              run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

            - name: Build and push container image to registry
              uses: docker/build-push-action@v5
              with:
                  file: ./src/Halcyon.Api/Dockerfile
                  tags: |
                      ghcr.io/${{ env.REPO }}:${{ steps.version_step.outputs.semVer }}
                      ghcr.io/${{ env.REPO }}:preview
                  context: .
                  push: true
                  provenance: false
                  build-args: |
                      VERSION=${{ steps.version_step.outputs.semVer }}
