name: Preview Build and Deploy

on:
    push:
        branches: ['feature/**', 'bugfix/**']
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        outputs:
            semVer: ${{ steps.gitversion.outputs.semVer }}

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0
              with:
                  versionSpec: '5.x'

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0
              with:
                  useConfigFile: true

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ github.token }}

            - name: Lowercase the repo name and username
              run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

            - name: Build and push container image to registry
              uses: docker/build-push-action@v5
              with:
                  push: true
                  provenance: false
                  tags: ghcr.io/${{ env.REPO }}:${{ steps.gitversion.outputs.semVer }}
                  file: ./src/Halcyon.Api/Dockerfile
                  build-args: |
                      VERSION=${{ steps.gitversion.outputs.semVer }}

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: Preview
            # url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
            url: ${{ vars.URL }}

        steps:
            - name: Lowercase the repo name and username
              run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  images: 'ghcr.io/${{ env.REPO }}:${{ needs.build.outputs.semVer }}'
